### ISSUE TITLE
Where is my copyright in css file?

### ISSUE THREAD

**Issue by QassimHassan** [pinceladasdaweb/mediabox#2]
Hello!

You told me added!

Where is my copyright in css file?

Please enter my copyright in css file.

Or I will make a complaint.

Good luck.

**Comment by pinceladasdaweb** [comment]
Man, look here: https://github.com/pinceladasdaweb/mediabox/blob/master/dist/mediabox.css

**Comment by QassimHassan** [comment]
Thanks.
