### ISSUE TITLE
Possible to get a 1.1.3 release?

### ISSUE THREAD

**Issue by nickdenardis** [pinceladasdaweb/mediabox#8]
https://github.com/pinceladasdaweb/mediabox/compare/1.1.2...master

Looks like a few commits to master since the last release. 

Possible to tag another release and push up to npmjs.com so projects can lock to a specific release?

**Comment by pinceladasdaweb** [comment]
Done. Thanks.

**Comment by nickdenardis** [comment]
You rock! Thanks 😄
